name: Project Update

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 12 * * Mon'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version
    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v2.0.2
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: Update Data
      run: mix vision_zero_dashboard.data --download='true' --years='2022,2023'
    - name: Format JSON
      run: |
        cat ./data/2022.json | jq -S > $RUNNER_TMP/2022.json && mv $RUNNER_TMP/2022.json ./data/2022.json
        cat ./data/2023.json | jq -S > $RUNNER_TMP/2023.json && mv $RUNNER_TMP/2023.json ./data/2023.json
    - name: Commit Data
      run: |
        git config user.email "mitchellhenkebot@users.noreply.github.com"
        git config user.name "Mitchell Henke Bot"

        git add _public/data
        git add data
        git add _public/index.html
        (git diff --quiet || git commit -m 'data update' && git push)
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
